[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/engine",
    "crates/sources",
    "crates/destinations",
    "crates/notifiers",
    "crates/cli",
    "crates/hub",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
backuppo-core = { path = "crates/core" }
backuppo-engine = { path = "crates/engine" }
backuppo-sources = { path = "crates/sources" }
backuppo-destinations = { path = "crates/destinations" }
backuppo-notifiers = { path = "crates/notifiers" }
