[package]
name = "backupper-destinations"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait = "0.1.92"
backupper-core.workspace = true
opendal = { version = "0.59.2", default-features = false, features = ["services-fs"] }
tokio = { version = "1", features = ["fs", "rt"] }
